name = "battle-buddy"
main = "src/server/worker.ts"
compatibility_date = "2024-09-23"

# Create a KV namespace with:
#   wrangler kv:namespace create ROOMS
# Then fill in the id and preview_id below.
[[kv_namespaces]]
binding = "ROOMS"
id = "553d972f51f3439da8035eade9b43803"
preview_id = "b1a3ce1843d7404198657b98c461d46f"
